# Generated by Django 4.2.7 on 2024-12-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edr_app', '0003_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('Information', 'Information'), ('Warning', 'Warning'), ('Error', 'Error'), ('Critical', 'Critical'), ('Verbose', 'Verbose')], max_length=20)),
                ('event_id', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edr_app.client')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='edr_app_win_timesta_717939_idx'), models.Index(fields=['source'], name='edr_app_win_source_dd1b3a_idx'), models.Index(fields=['level'], name='edr_app_win_level_451d5b_idx')],
            },
        ),
    ]
