# Generated by Django 4.2.7 on 2024-12-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edr_app', '0004_windowseventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
