# Generated by Django 4.2.7 on 2026-03-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edr_app', '0006_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_lolbin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='is_suspicious_chain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='parent_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='sha256_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='ioc_matched',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=20),
        ),
        migrations.CreateModel(
            name='ThreatIntelIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('source', models.CharField(max_length=50)),
                ('threat_type', models.CharField(blank=True, max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='edr_app_thr_ip_addr_580a22_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256_hash', models.CharField(max_length=64, unique=True)),
                ('malware_name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sha256_hash'], name='edr_app_thr_sha256__0ec51a_idx')],
            },
        ),
    ]
