# Generated by Django 4.2.7 on 2026-03-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edr_app', '0007_process_is_lolbin_process_is_suspicious_chain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciousactivity',
            name='event_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['client', 'ioc_matched', 'type'], name='edr_app_sus_client__22ebf8_idx'),
        ),
    ]
