# Generated by Django 4.2.7 on 2026-03-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edr_app', '0008_suspiciousactivity_event_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='local_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='local_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='remote_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='remote_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
