# Generated by Django 4.2.7 on 2026-03-31 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edr_app', '0009_port_local_ip_port_local_port_port_remote_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(blank=True, help_text='e.g. explorer.exe', max_length=255)),
                ('process_path', models.CharField(blank=True, help_text='e.g. C:\\Windows\\System32\\', max_length=500)),
                ('sha256_hash', models.CharField(blank=True, help_text='Full SHA256 hex string', max_length=64)),
                ('match_mode', models.CharField(choices=[('NAME_ONLY', 'Name Only'), ('NAME_AND_PATH', 'Name + Path'), ('HASH_ONLY', 'SHA256 Hash Only'), ('ALL', 'Name + Path + Hash')], default='NAME_AND_PATH', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why this process is excluded')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for permanent exclusion', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['process_name', 'is_active'], name='edr_app_exc_process_9d979a_idx'), models.Index(fields=['sha256_hash', 'is_active'], name='edr_app_exc_sha256__59af24_idx')],
            },
        ),
    ]
