# Generated by Django 4.2.7 on 2026-04-06 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edr_app', '0010_exclusionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciousactivity',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, help_text='Groups related alerts from same attack chain', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PROCESS_START', 'Process Started'), ('NETWORK_CONNECT', 'Network Connection'), ('HASH_MATCH', 'Malware Hash Detected'), ('IP_MATCH', 'Blacklisted IP Connection'), ('LOLBIN_CHAIN', 'LOLBin Process Chain'), ('RANSOMWARE_PRECURSOR', 'Ransomware Precursor Tool')], db_index=True, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('raw_data', models.TextField(default='{}', help_text='JSON-encoded event data')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='edr_app.client')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='edr_app.port')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='edr_app.process')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='edr_app.event'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['client', 'event_type'], name='edr_app_eve_client__cb4057_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['client', 'timestamp'], name='edr_app_eve_client__934c98_idx'),
        ),
    ]
