# Generated by Django 4.2.7 on 2026-04-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edr_app', '0011_suspiciousactivity_correlation_id_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciousactivity',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
