# Generated by Django 4.2.7 on 2026-04-06 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edr_app', '0012_suspiciousactivity_is_acknowledged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig_id', models.CharField(default='SIG-000', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('plain_title', models.CharField(max_length=200)),
                ('plain_explanation', models.TextField()),
                ('plain_action', models.TextField()),
                ('mitre_id', models.CharField(blank=True, max_length=20)),
                ('mitre_tactic', models.CharField(blank=True, choices=[('execution', 'Execution'), ('defense_evasion', 'Defense Evasion'), ('command_control', 'Command and Control'), ('discovery', 'Discovery'), ('lateral_movement', 'Lateral Movement'), ('impact', 'Impact'), ('persistence', 'Persistence')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='edr_app.suspiciousactivity')),
                ('events', models.ManyToManyField(blank=True, related_name='signatures', to='edr_app.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
