# Generated by Django 4.2.7 on 2026-04-07 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edr_app', '0013_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suspiciousactivity',
            options={'ordering': ['-last_seen']},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='edr_app_eve_client__cb4057_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='event_client_ts_idx',
            old_name='edr_app_eve_client__934c98_idx',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='is_acknowledged',
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='false_positive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('false_positive', 'False Positive'), ('in_incident', 'In Incident'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'timestamp'], name='event_type_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp'], name='event_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['severity', 'last_seen'], name='alert_sev_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['client', 'last_seen'], name='alert_client_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['last_seen'], name='alert_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['status'], name='alert_status_idx'),
        ),
    ]
