# Generated by Django 4.2.7 on 2026-04-07 12:15

from django.db import migrations


def rename_status(apps, schema_editor):
    M = apps.get_model('edr_app', 'SuspiciousActivity')
    M.objects.filter(status='acknowledged').update(status='in_response')


def reverse_rename(apps, schema_editor):
    M = apps.get_model('edr_app', 'SuspiciousActivity')
    M.objects.filter(status='in_response').update(status='acknowledged')


class Migration(migrations.Migration):

    dependencies = [
        ('edr_app', '0014_alter_suspiciousactivity_options_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_status, reverse_rename),
    ]
