# Generated by Django 4.2.7 on 2026-04-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edr_app', '0015_rename_acknowledged_to_in_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspiciousactivity',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_response', 'In Response'), ('false_positive', 'False Positive'), ('in_incident', 'In Incident'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
    ]
