# Generated by Django 4.2.7 on 2026-04-07 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edr_app', '0017_incident_incidentcomment_incidentactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('events', 'Events Report'), ('alerts', 'Alerts Report'), ('incidents', 'Incidents Report'), ('compliance', 'PP-167 Compliance Report')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField(default=0)),
                ('filters_applied', models.TextField(blank=True, default='{}')),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'generated_at'], name='edr_app_rep_report__9444e9_idx')],
            },
        ),
    ]
