# Generated by Django 4.2.7 on 2026-04-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edr_app', '0018_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command',
        ),
    ]
